---
version: "3.8"

services:
  mongodb:
    image: mongo:${MONGO_VER}
    env_file:
      - "creds.env"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
  mongo_express:
    image: mongo-express:${MONGO_EXPRESS_VER}
    env_file:
      - "creds.env"
      - "dev.env"
    ports:
      - 8081:8081

volumes:
  mongodb_data: {}
